
# DataSource personalizado
spring.datasource.driver.class=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/prueba_gestopago
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.table=flyway_schema_history
spring.flyway.schemas=public

# GestoPago
gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678

# Intervalo (3600000 = 1 hora)
gestopago.auth.refresh-rate-ms=3600000

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

logging.level.root=INFO
logging.level.com.tu.paquete=DEBUG

# API
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
server.port=8081

# URL (localhost)
openapi.url.dev=http://localhost:8081
openapi.description.dev=Local Development Server

# Onboarding
# Saldo con el que el sistema abre automáticamente toda cuenta nueva
app.cuenta.saldo-inicial=0.00
# Límite de sesión (minutos de inactividad)
app.login.session-timeout-minutes=5

# Llave AES para cifrar dato biométrico y token de sesión
app.seguridad.aes-key=ySyJiU10dr71D5cBm5n4EUZ+qwJtJj/eW7foLQp63Z0=